"""add file_hash

Revision ID: add_file_hash
Revises: de761d78c1de
Create Date: 2025-04-23 02:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_file_hash'
down_revision = 'de761d78c1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_unique_constraint('uq_documents_file_hash', 'documents', ['file_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_file_hash', 'documents', type_='unique')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ### 