"""update_user_model_with_full_name_and_department

Revision ID: b15f35c9a49d
Revises: 
Create Date: 2025-04-22 13:59:53.434999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b15f35c9a49d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add new columns as nullable
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing data
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE users 
        SET full_name = CONCAT_WS(' ', first_name, last_name)
        WHERE first_name IS NOT NULL OR last_name IS NOT NULL
    """))
    
    # Make full_name not nullable
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               nullable=False)
    
    # Drop old columns
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Update old columns from full_name
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE users 
        SET first_name = split_part(full_name, ' ', 1),
            last_name = substr(full_name, length(split_part(full_name, ' ', 1)) + 2)
    """))
    
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'department')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
